# Generated by Django 5.1.8 on 2025-05-29 11:33

import django.db.models.deletion
import speaker.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakerProfile",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="portal.basemodel",
                    ),
                ),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            (
                                speaker.constants.ApplicationStatus["PENDING"],
                                speaker.constants.ApplicationStatus["PENDING"],
                            ),
                            (
                                speaker.constants.ApplicationStatus["APPROVED"],
                                speaker.constants.ApplicationStatus["APPROVED"],
                            ),
                            (
                                speaker.constants.ApplicationStatus["REJECTED"],
                                speaker.constants.ApplicationStatus["REJECTED"],
                            ),
                            (
                                speaker.constants.ApplicationStatus["CANCELLED"],
                                speaker.constants.ApplicationStatus["CANCELLED"],
                            ),
                        ],
                        default=speaker.constants.ApplicationStatus["PENDING"],
                        max_length=50,
                    ),
                ),
                ("code", models.CharField(blank=True, unique=True)),
                ("name", models.CharField(blank=True, null=True)),
                ("biography", models.CharField(blank=True, null=True)),
                ("avatar_url", models.CharField(blank=True, null=True)),
                ("email", models.CharField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, null=True)),
                ("locale", models.CharField(blank=True, null=True)),
                ("has_arrived", models.BooleanField(blank=True, null=True)),
                ("submissions", models.JSONField(blank=True, null=True)),
                ("answers", models.JSONField(blank=True, null=True)),
                (
                    "additional_comments",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
            bases=("portal.basemodel",),
        ),
    ]
