# Generated by Django 5.2.13 on 2026-09-15 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portal", "0007_conference_coc_url_conference_donate_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "speaker_module_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Turn the speaker portal on for this edition.",
                    ),
                ),
                (
                    "conference",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_settings",
                        to="portal.conference",
                    ),
                ),
            ],
            options={
                "verbose_name": "speaker settings",
                "verbose_name_plural": "speaker settings",
            },
        ),
    ]
