# Generated by Django 5.2.13 on 2026-09-15 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import speakers.models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("portal", "0007_conference_coc_url_conference_donate_url_and_more"),
        ("speakers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PresenterRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stable key, e.g. PANELIST; upper case.",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "email_word",
                    models.CharField(
                        default="speaker",
                        help_text='How emails address them: "thank you for being a <word>".',
                        max_length=40,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive roles are kept on existing rows but not offered.",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presenter_roles",
                        to="portal.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SessionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stable key, e.g. WORKSHOP; upper case.",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "is_content",
                    models.BooleanField(
                        default=True,
                        help_text="Needs a confirmed presenter to be confirmed. Off for the opening, breaks and other program items, which are confirmed as created.",
                    ),
                ),
                ("default_duration_minutes", models.PositiveIntegerField(default=30)),
                (
                    "default_delivery",
                    models.CharField(
                        choices=[("LIVE", "Live"), ("PRE_RECORDED", "Pre-recorded")],
                        default="LIVE",
                        max_length=16,
                    ),
                ),
                (
                    "spans_all_channels",
                    models.BooleanField(
                        default=False,
                        help_text="On the schedule, takes the whole grid rather than one channel.",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive types are kept on existing sessions but not offered.",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_types",
                        to="portal.conference",
                    ),
                ),
                (
                    "default_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preselected when adding or inviting a presenter.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="speakers.presenterrole",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Who can be on a session of this type.",
                        related_name="session_types",
                        to="speakers.presenterrole",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="presenterrole",
            constraint=models.UniqueConstraint(
                fields=("conference", "code"), name="speakers_role_code_per_edition"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessiontype",
            constraint=models.UniqueConstraint(
                fields=("conference", "code"), name="speakers_type_code_per_edition"
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="default_premiere_location",
            field=models.CharField(
                choices=[
                    ("DISCORD", "Watch party on Discord"),
                    ("YOUTUBE", "YouTube Premiere"),
                ],
                default="DISCORD",
                help_text="Where pre-recorded sessions premiere unless a session says otherwise.",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="DiscordChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "channel_id",
                    models.CharField(
                        blank=True,
                        help_text="The numeric Discord channel id.",
                        max_length=32,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("STAGE", "Stage"),
                            ("VOICE", "Voice"),
                            ("TEXT", "Text"),
                            ("FORUM", "Forum"),
                        ],
                        default="STAGE",
                        max_length=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discord_channels",
                        to="portal.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Presenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=100)),
                (
                    "email",
                    models.EmailField(
                        help_text="Invitation and reminder target.", max_length=254
                    ),
                ),
                ("pronouns", models.CharField(blank=True, max_length=50)),
                (
                    "bio_md",
                    models.TextField(
                        blank=True, help_text="Markdown.", verbose_name="bio"
                    ),
                ),
                (
                    "headshot",
                    models.ImageField(blank=True, upload_to="speakers/headshots/"),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        max_length=64,
                        validators=[speakers.models.validate_timezone],
                    ),
                ),
                ("website_url", models.URLField(blank=True)),
                ("github_username", models.CharField(blank=True, max_length=39)),
                ("mastodon_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("bluesky_username", models.CharField(blank=True, max_length=100)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Off hides the bio, headshot and links on the public site; the name still appears on their sessions.",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presenters",
                        to="portal.conference",
                    ),
                ),
                (
                    "liaison",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organizer or volunteer looking after this presenter.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liaison_for_presenters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presenter_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="speakers.sessiontype",
                    ),
                ),
                (
                    "delivery",
                    models.CharField(
                        blank=True,
                        choices=[("LIVE", "Live"), ("PRE_RECORDED", "Pre-recorded")],
                        help_text="Blank takes the type's default; filled in on save.",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=100)),
                (
                    "summary_md",
                    models.TextField(
                        blank=True, help_text="Markdown.", verbose_name="summary"
                    ),
                ),
                (
                    "outline_md",
                    models.TextField(
                        blank=True, help_text="Markdown.", verbose_name="outline"
                    ),
                ),
                (
                    "prerequisites_md",
                    models.TextField(
                        blank=True, help_text="Markdown.", verbose_name="prerequisites"
                    ),
                ),
                (
                    "audience_md",
                    models.TextField(
                        blank=True, help_text="Markdown.", verbose_name="audience"
                    ),
                ),
                (
                    "notes_md",
                    models.TextField(
                        blank=True,
                        help_text="Markdown. Never public.",
                        verbose_name="internal notes",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ALL", "All levels"),
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Language code, e.g. en, pt-br.",
                        max_length=10,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Defaults from the kind when left blank.",
                        null=True,
                    ),
                ),
                (
                    "video_length_limit_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("youtube_url", models.URLField(blank=True)),
                ("youtube_publish_at", models.DateTimeField(blank=True, null=True)),
                (
                    "premiere_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DISCORD", "Watch party on Discord"),
                            ("YOUTUBE", "YouTube Premiere"),
                        ],
                        help_text="Blank uses the edition's default.",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("INVITED", "Invited"),
                            ("CONFIRMED", "Confirmed"),
                            ("SCHEDULED", "Scheduled"),
                            ("PUBLISHED", "Published"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Explicit publish switch (design §11.5).",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="portal.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("start_utc", models.DateTimeField()),
                (
                    "end_utc",
                    models.DateTimeField(
                        blank=True,
                        help_text="Defaults to start plus the session duration.",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="speakers.discordchannel",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_slots",
                        to="portal.conference",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot",
                        to="speakers.session",
                    ),
                ),
            ],
            options={
                "ordering": ["start_utc"],
            },
        ),
        migrations.CreateModel(
            name="SessionPresenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_presenters",
                        to="speakers.presenterrole",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conference",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_presenters",
                        to="portal.conference",
                    ),
                ),
                (
                    "presenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_presenters",
                        to="speakers.presenter",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_presenters",
                        to="speakers.session",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="presenters",
            field=models.ManyToManyField(
                blank=True,
                related_name="sessions",
                through="speakers.SessionPresenter",
                to="speakers.presenter",
            ),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("action", models.CharField(max_length=64)),
                ("message", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="speaker_activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="speaker_activity",
                        to="portal.conference",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="speakers_ac_content_2228a6_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="discordchannel",
            constraint=models.UniqueConstraint(
                fields=("conference", "name"), name="speakers_channel_name_per_edition"
            ),
        ),
        migrations.AddConstraint(
            model_name="presenter",
            constraint=models.UniqueConstraint(
                fields=("conference", "email"),
                name="speakers_presenter_email_per_edition",
            ),
        ),
        migrations.AddConstraint(
            model_name="presenter",
            constraint=models.UniqueConstraint(
                fields=("conference", "slug"),
                name="speakers_presenter_slug_per_edition",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionpresenter",
            constraint=models.UniqueConstraint(
                fields=("session", "presenter"),
                name="speakers_presenter_once_per_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                fields=("conference", "slug"), name="speakers_session_slug_per_edition"
            ),
        ),
    ]
