# Generated by Django 5.2.13 on 2026-09-15 22:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_conference_coc_url_conference_donate_url_and_more"),
        ("speakers", "0003_invitations"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakersettings",
            name="default_video_length_limit_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Length limit for pre-recorded videos unless a session says otherwise.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="translation_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                default=list,
                help_text="Language codes the team translates transcripts into; one post-production item is created per language.",
                size=None,
            ),
        ),
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("PRESENTER", "Per presenter (keyed by kind and role)"),
                            ("SESSION", "Per session (keyed by kind and delivery)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("WORKSHOP", "Workshop"),
                            ("PANEL", "Panel"),
                            ("PYJAM", "PyJam performance"),
                            ("TALK", "Talk"),
                            ("LIGHTNING", "Lightning talk"),
                            ("OPENING", "Opening"),
                            ("CLOSING", "Closing"),
                            ("KEYNOTE", "Keynote"),
                            ("ANNOUNCEMENT", "Announcement"),
                            ("BREAK", "Break"),
                            ("SOCIAL", "Social"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRESENTER", "Presenter"),
                            ("CO_PRESENTER", "Co-presenter"),
                            ("PANELIST", "Panelist"),
                            ("MODERATOR", "Moderator"),
                            ("HOST", "Host"),
                            ("PERFORMER", "Performer"),
                        ],
                        help_text="Presenter scope only.",
                        max_length=16,
                    ),
                ),
                (
                    "delivery",
                    models.CharField(
                        blank=True,
                        choices=[("LIVE", "Live"), ("PRE_RECORDED", "Pre-recorded")],
                        help_text="Session scope only.",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_templates",
                        to="portal.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["scope", "kind", "role", "delivery"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "owner",
                    models.CharField(
                        choices=[("SPEAKER", "Speaker"), ("ORGANIZER", "Organizer")],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description_md", models.TextField(blank=True, help_text="Markdown.")),
                (
                    "due_anchor",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "INVITATION_ACCEPTED",
                                "Days after the invitation is accepted",
                            ),
                            ("CONFERENCE_START", "Days before the conference starts"),
                            ("SESSION_START", "Days before the session starts"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "due_offset_days",
                    models.IntegerField(
                        default=0,
                        help_text="Days after the invitation is accepted, or days before the conference or session starts.",
                    ),
                ),
                (
                    "auto_complete_rule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bio_and_headshot", "Bio and headshot are filled in"),
                            ("handbook_read", "Speaker guide read (current version)"),
                            ("invitation_sent", "Invitation sent"),
                            ("invitation_accepted", "Invitation accepted"),
                            ("session_scheduled", "Session has a slot"),
                            ("pretix_registered", "Registered on pretix"),
                            (
                                "asset_exists",
                                "A ready asset of the required kind exists",
                            ),
                            ("video_length_ok", "Video length within the limit"),
                            ("youtube_published", "YouTube URL and publish time set"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "requires_asset_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RAW_VIDEO", "Raw video (performer upload)"),
                            ("INTRO", "Intro (MC)"),
                            ("OUTRO", "Outro (MC)"),
                            ("PROCESSED_VIDEO", "Processed video (final cut)"),
                            ("TRANSCRIPT", "Transcript"),
                            ("TRANSLATION", "Translation"),
                            ("TITLE_CARD", "Title card"),
                            ("THUMBNAIL", "Thumbnail"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "requires_asset_language",
                    models.CharField(
                        blank=True,
                        help_text='A language code, or "session" for the session language.',
                        max_length=10,
                    ),
                ),
                (
                    "per_translation_language",
                    models.BooleanField(
                        default=False,
                        help_text="Instantiate one item per translation language of the edition.",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Required items gate the session being confirmed.",
                    ),
                ),
                (
                    "assignee_default",
                    models.CharField(
                        choices=[
                            ("UNASSIGNED", "Unassigned"),
                            ("LIAISON", "The presenter's liaison"),
                        ],
                        default="UNASSIGNED",
                        help_text="Organizer items only.",
                        max_length=16,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="speakers.checklisttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="checklisttemplate",
            constraint=models.UniqueConstraint(
                fields=("conference", "scope", "kind", "role", "delivery"),
                name="speakers_template_key_per_edition",
            ),
        ),
    ]
