# Generated by Django 5.2.13 on 2026-09-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0003_checklists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presenter",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="session",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100),
        ),
    ]
