# Pretix settings and reconciliation, reminder digests and their log, and the
# speaker guide with read receipts (tasks 2.7 to 2.9), plus the two nightly
# schedules in django-celery-beat. The schedules are data (editable under
# "Periodic tasks"); seeding them here only gives a fresh database the same
# default. Names are literal so the migration stays replayable.

# Generated by Django 5.2.13 on 2026-09-20 21:02

import django.db.models.deletion
from django.db import migrations, models

import speakers.encryption
import speakers.models

PRETIX_TASK_NAME = "Reconcile pretix orders for the speaker portal"
PRETIX_TASK_PATH = "speakers.tasks.pretix_reconcile_task"


def seed_pretix_task(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    nightly, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="2",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )
    PeriodicTask.objects.get_or_create(
        name=PRETIX_TASK_NAME,
        defaults={
            "task": PRETIX_TASK_PATH,
            "crontab": nightly,
            "description": (
                "Page through pretix orders modified since the last run so "
                "missed webhooks and backend edits are caught."
            ),
        },
    )


def unseed_pretix_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name=PRETIX_TASK_NAME).delete()


DIGEST_TASK_NAME = "Send speaker checklist digests"
DIGEST_TASK_PATH = "speakers.tasks.send_checklist_digests_task"


def seed_digest_task(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    morning, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="7",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )
    PeriodicTask.objects.get_or_create(
        name=DIGEST_TASK_NAME,
        defaults={
            "task": DIGEST_TASK_PATH,
            "crontab": morning,
            "description": (
                "Email each presenter and assignee their open checklist items "
                "due within 7, 3 and 1 days; each reminder is sent once."
            ),
        },
    )


def unseed_digest_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name=DIGEST_TASK_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("portal", "0007_conference_coc_url_conference_donate_url_and_more"),
        ("speakers", "0003_checklists"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakersettings",
            name="conference_timezone",
            field=models.CharField(
                default="UTC",
                help_text="The organizers' default display timezone; the conference itself has none.",
                max_length=64,
                validators=[speakers.models.validate_timezone],
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="organizers_email",
            field=models.EmailField(
                blank=True,
                help_text="Where unassigned organizer reminders go; blank sends them to every staff account.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="pretix_api_token",
            field=speakers.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="pretix_base_url",
            field=models.URLField(
                default="https://pretix.eu/api/v1/",
                help_text="The pretix API root, ending in /api/v1/.",
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="pretix_create_vouchers",
            field=models.BooleanField(
                default=False,
                help_text="Create a pretix voucher per presenter (not implemented yet).",
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="pretix_event",
            field=models.CharField(
                blank=True,
                help_text="Event slug; blank uses the conference's pretix event slug.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="pretix_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="pretix_organizer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="pretix_webhook_secret",
            field=speakers.encryption.EncryptedTextField(
                blank=True, help_text="Sent by pretix as ?secret= on the webhook URL."
            ),
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("threshold_days", models.PositiveSmallIntegerField()),
                ("recipient", models.EmailField(max_length=254)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conference",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminder_logs",
                        to="portal.conference",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="speakers.checklistitem",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "threshold_days"), name="speakers_reminder_once"
                    )
                ],
            },
        ),
        migrations.RunPython(seed_pretix_task, unseed_pretix_task),
        migrations.RunPython(seed_digest_task, unseed_digest_task),
    ]
