# Generated by Django 5.2.13 on 2026-09-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_conference_coc_url_conference_donate_url_and_more"),
        ("speakers", "0004_pretix_reminders_guide"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="handbook",
            name="speakers_handbook_version",
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="requires_handbook",
            field=models.SlugField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="checklisttemplateitem",
            name="requires_handbook",
            field=models.SlugField(
                blank=True,
                help_text='Guide key for the "read the guide" rule; blank means "speaker".',
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="handbook",
            name="key",
            field=models.SlugField(
                default="speaker",
                help_text="Short identifier checklist lines refer to, e.g. workshop.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="handbook",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Where the guide lives, e.g. https://conference.pyladies.com/docs/",
            ),
        ),
        migrations.AlterField(
            model_name="handbook",
            name="body_md",
            field=models.TextField(
                blank=True, help_text="Optional note shown above the link. Markdown."
            ),
        ),
        migrations.AddConstraint(
            model_name="handbook",
            constraint=models.UniqueConstraint(
                fields=("conference", "key", "version"),
                name="speakers_handbook_version",
            ),
        ),
    ]
