# Generated by Django 5.2.13 on 2026-09-15 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_conference_coc_url_conference_donate_url_and_more"),
        ("speakers", "0004_checklist_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "owner",
                    models.CharField(
                        choices=[("SPEAKER", "Speaker"), ("ORGANIZER", "Organizer")],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description_md", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To do"),
                            ("DONE", "Done"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="TODO",
                        max_length=16,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "auto_complete_rule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bio_and_headshot", "Bio and headshot are filled in"),
                            ("handbook_read", "Speaker guide read (current version)"),
                            ("invitation_sent", "Invitation sent"),
                            ("invitation_accepted", "Invitation accepted"),
                            ("session_scheduled", "Session has a slot"),
                            ("pretix_registered", "Registered on pretix"),
                            (
                                "asset_exists",
                                "A ready asset of the required kind exists",
                            ),
                            ("video_length_ok", "Video length within the limit"),
                            ("youtube_published", "YouTube URL and publish time set"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "requires_asset_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RAW_VIDEO", "Raw video (performer upload)"),
                            ("INTRO", "Intro (MC)"),
                            ("OUTRO", "Outro (MC)"),
                            ("PROCESSED_VIDEO", "Processed video (final cut)"),
                            ("TRANSCRIPT", "Transcript"),
                            ("TRANSLATION", "Translation"),
                            ("TITLE_CARD", "Title card"),
                            ("THUMBNAIL", "Thumbnail"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "requires_asset_language",
                    models.CharField(blank=True, max_length=10),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_checklist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_items",
                        to="portal.conference",
                    ),
                ),
                (
                    "presenter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="speakers.presenter",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="speakers.session",
                    ),
                ),
                (
                    "template_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="speakers.checklisttemplateitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("template_item__isnull", False)),
                        fields=(
                            "template_item",
                            "presenter",
                            "session",
                            "requires_asset_language",
                        ),
                        name="speakers_item_once_per_target",
                        nulls_distinct=False,
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("presenter__isnull", False),
                            ("session__isnull", False),
                            _connector="OR",
                        ),
                        name="speakers_item_has_target",
                    ),
                ],
            },
        ),
    ]
