# Generated by Django 5.2.13 on 2026-09-21 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0005_multiple_guides"),
        ("volunteer", "0015_alter_team_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitem",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="An item is owned by a person or by a team, not both.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checklist_items",
                to="volunteer.team",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplateitem",
            name="default_team_name",
            field=models.CharField(
                blank=True,
                help_text='With "A named team": the team\'s name, matched per edition so templates clone forward.',
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplateitem",
            name="assignee_default",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("LIAISON", "The presenter's liaison"),
                    ("TEAM", "A named team"),
                ],
                default="UNASSIGNED",
                help_text="Organizer items only.",
                max_length=16,
            ),
        ),
    ]
