# Generated by Django 5.2.13 on 2026-09-15 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0005_alter_pretixorder_conference"),
        ("portal", "0007_conference_coc_url_conference_donate_url_and_more"),
        ("speakers", "0005_checklist_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="presenter",
            name="pretix_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Manual link when the presenter registered under another email address; wins over email matching.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_presenters",
                to="attendee.pretixorder",
            ),
        ),
        migrations.CreateModel(
            name="Handbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(default="Speaker guide", max_length=200)),
                ("body_md", models.TextField(blank=True, help_text="Markdown.")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handbooks",
                        to="portal.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="HandbookReadReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conference",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handbook_receipts",
                        to="portal.conference",
                    ),
                ),
                (
                    "handbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="speakers.handbook",
                    ),
                ),
                (
                    "presenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handbook_receipts",
                        to="speakers.presenter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("RAW_VIDEO", "Raw video (performer upload)"),
                            ("INTRO", "Intro (MC)"),
                            ("OUTRO", "Outro (MC)"),
                            ("PROCESSED_VIDEO", "Processed video (final cut)"),
                            ("TRANSCRIPT", "Transcript"),
                            ("TRANSLATION", "Translation"),
                            ("TITLE_CARD", "Title card"),
                            ("THUMBNAIL", "Thumbnail"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Transcripts and translations.",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADING", "Uploading"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="UPLOADING",
                        max_length=16,
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="speakers/media/")),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "notes_md",
                    models.TextField(blank=True, help_text="Reviewer notes. Markdown."),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_assets",
                        to="portal.conference",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="speakers.session",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_media_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="handbook",
            constraint=models.UniqueConstraint(
                fields=("conference", "version"), name="speakers_handbook_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="handbookreadreceipt",
            constraint=models.UniqueConstraint(
                fields=("presenter", "handbook"), name="speakers_receipt_once"
            ),
        ),
    ]
