# Adds the change-notice flags and the password reminder, and schedules the
# daily checklist-update emails. Names are literal so the migration stays
# replayable.

# Generated by Django 5.2.13 on 2026-09-22 04:35

from django.db import migrations, models

TASK_NAME = "Send speaker checklist change notices"
TASK_PATH = "speakers.tasks.send_checklist_change_notices_task"


def seed_periodic_task(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    morning, _ = CrontabSchedule.objects.get_or_create(
        minute="30",
        hour="7",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )
    PeriodicTask.objects.get_or_create(
        name=TASK_NAME,
        defaults={
            "task": TASK_PATH,
            "crontab": morning,
            "description": (
                "Email presenters and assignees the checklist items added or "
                "changed since they were last told; nothing is sent otherwise."
            ),
        },
    )


def unseed_periodic_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name=TASK_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0006_team_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitem",
            name="pending_notice",
            field=models.CharField(
                blank=True,
                choices=[("NEW", "New item"), ("CHANGED", "Changed item")],
                editable=False,
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="pending_since",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="presenter",
            name="password_reminder_dismissed",
            field=models.BooleanField(
                default=False,
                help_text="The presenter chose to keep signing in with emailed codes.",
            ),
        ),
        migrations.RunPython(seed_periodic_task, unseed_periodic_task),
    ]
