# Generated by Django 5.2.13 on 2026-09-15 23:53

from django.db import migrations, models

import speakers.encryption


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0007_reevaluate_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakersettings",
            name="pretix_api_token",
            field=speakers.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="pretix_base_url",
            field=models.URLField(
                default="https://pretix.eu/api/v1/",
                help_text="The pretix API root, ending in /api/v1/.",
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="pretix_create_vouchers",
            field=models.BooleanField(
                default=False,
                help_text="Create a pretix voucher per presenter (not implemented yet).",
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="pretix_event",
            field=models.CharField(
                blank=True,
                help_text="Event slug; blank uses the conference's pretix event slug.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="pretix_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="pretix_organizer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="pretix_webhook_secret",
            field=speakers.encryption.EncryptedTextField(
                blank=True, help_text="Sent by pretix as ?secret= on the webhook URL."
            ),
        ),
    ]
