"""Give the columns added since 0005 a database-level default.

Django drops the default it used to backfill an ``AddField``, leaving the
column NOT NULL with nothing behind it. That is fine while the code and the
schema move together, and wrong during a deploy: the release step runs
``migrate`` before the new release is serving, so for a few seconds an old
process inserts a row without the new column and Postgres refuses it:

    null value in column "default_team_name" of relation
    "speakers_checklisttemplateitem" violates not-null constraint

``db_default`` (Django 5) puts the default in the schema as well as in
Python, which closes that window. Each field keeps its ``default`` too: with
only a ``db_default`` an unsaved instance holds a sentinel rather than the
value, and code that reads the attribute before saving (a ``clean()``, say)
sees the wrong thing. See docs/developer/deployment.md.
"""

# Generated by Django 5.2.13 on 2026-09-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0007_onboarding_and_change_notices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistitem",
            name="pending_notice",
            field=models.CharField(
                blank=True,
                choices=[("NEW", "New item"), ("CHANGED", "Changed item")],
                db_default="",
                default="",
                editable=False,
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="requires_handbook",
            field=models.SlugField(
                blank=True, db_default="", default="", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplateitem",
            name="default_team_name",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text='With "A named team": the team\'s name, matched per edition so templates clone forward.',
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplateitem",
            name="requires_handbook",
            field=models.SlugField(
                blank=True,
                db_default="",
                default="",
                help_text='Guide key for the "read the guide" rule; blank means "speaker".',
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="handbook",
            name="key",
            field=models.SlugField(
                db_default="speaker",
                default="speaker",
                help_text="Short identifier checklist lines refer to, e.g. workshop.",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="presenter",
            name="password_reminder_dismissed",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="The presenter chose to keep signing in with emailed codes.",
            ),
        ),
    ]
