"""Give every column added after its table a database-level default.

Django backfills a column it adds and then **drops** the default, leaving it
NOT NULL with nothing behind it. That is fine while the code and the schema
move together, and wrong during a deploy: the release step runs ``migrate``
before the new release is serving, so for a few seconds an old process
inserts a row without the new column and Postgres refuses it:

    null value in column "default_team_name" of relation
    "speakers_checklisttemplateitem" violates not-null constraint

``db_default`` (Django 5) puts the default in the schema as well as in
Python, which closes that window. Each field keeps its ``default`` too: with
only a ``db_default`` an unsaved instance holds a sentinel rather than the
value, and code that reads the attribute before saving (a ``clean()``, say)
sees the wrong thing.

``tests/speakers/test_deploy_window.py`` reads the migration graph and
audits every such column, so the next one cannot be forgotten. See
docs/developer/deployment.md.
"""

# Generated by Django 5.2.13 on 2026-09-22 18:30

import django.contrib.postgres.fields
from django.db import migrations, models

import speakers.encryption
import speakers.models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0007_onboarding_and_change_notices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistitem",
            name="pending_notice",
            field=models.CharField(
                blank=True,
                choices=[("NEW", "New item"), ("CHANGED", "Changed item")],
                db_default="",
                default="",
                editable=False,
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="requires_handbook",
            field=models.SlugField(
                blank=True, db_default="", default="", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplateitem",
            name="default_team_name",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text='With "A named team": the team\'s name, matched per edition so templates clone forward.',
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplateitem",
            name="requires_handbook",
            field=models.SlugField(
                blank=True,
                db_default="",
                default="",
                help_text='Guide key for the "read the guide" rule; blank means "speaker".',
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="handbook",
            name="key",
            field=models.SlugField(
                db_default="speaker",
                default="speaker",
                help_text="Short identifier checklist lines refer to, e.g. workshop.",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="handbook",
            name="url",
            field=models.URLField(
                blank=True,
                db_default="",
                default="",
                help_text="Where the guide lives, e.g. https://conference.pyladies.com/docs/",
            ),
        ),
        migrations.AlterField(
            model_name="presenter",
            name="password_reminder_dismissed",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="The presenter chose to keep signing in with emailed codes.",
            ),
        ),
        migrations.AlterField(
            model_name="speakersettings",
            name="conference_timezone",
            field=models.CharField(
                db_default="UTC",
                default="UTC",
                help_text="The organizers' default display timezone; the conference itself has none.",
                max_length=64,
                validators=[speakers.models.validate_timezone],
            ),
        ),
        migrations.AlterField(
            model_name="speakersettings",
            name="organizers_email",
            field=models.EmailField(
                blank=True,
                db_default="",
                default="",
                help_text="Where unassigned organizer reminders go; blank sends them to every staff account.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="speakersettings",
            name="pretix_api_token",
            field=speakers.encryption.EncryptedTextField(
                blank=True, db_default="", default=""
            ),
        ),
        migrations.AlterField(
            model_name="speakersettings",
            name="pretix_base_url",
            field=models.URLField(
                db_default="https://pretix.eu/api/v1/",
                default="https://pretix.eu/api/v1/",
                help_text="The pretix API root, ending in /api/v1/.",
            ),
        ),
        migrations.AlterField(
            model_name="speakersettings",
            name="pretix_create_vouchers",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Create a pretix voucher per presenter (not implemented yet).",
            ),
        ),
        migrations.AlterField(
            model_name="speakersettings",
            name="pretix_event",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Event slug; blank uses the conference's pretix event slug.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="speakersettings",
            name="pretix_organizer",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="speakersettings",
            name="pretix_webhook_secret",
            field=speakers.encryption.EncryptedTextField(
                blank=True,
                db_default="",
                default="",
                help_text="Sent by pretix as ?secret= on the webhook URL.",
            ),
        ),
        migrations.AlterField(
            model_name="speakersettings",
            name="translation_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                db_default=models.Value("{}"),
                default=list,
                help_text="Language codes the team translates transcripts into; one post-production item is created per language.",
                size=None,
            ),
        ),
    ]
