# Generated by Django 5.2.13 on 2026-09-23 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0008_database_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklisttemplateitem",
            name="once_per_presenter",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="One item per presenter, not one per session (for lines in a per-session template, e.g. read the workshop guide).",
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplate",
            name="kind",
            field=models.ForeignKey(
                blank=True,
                help_text="Not used by the general (every presenter) template.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checklist_templates",
                to="speakers.sessiontype",
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplate",
            name="scope",
            field=models.CharField(
                choices=[
                    ("GENERAL", "Every presenter (once per edition)"),
                    ("PRESENTER", "Per presenter per session (keyed by kind and role)"),
                    ("SESSION", "Per session (keyed by kind and delivery)"),
                ],
                max_length=16,
            ),
        ),
    ]
