# Generated by Django 5.2.13 on 2026-09-16 00:00

import django.db.models.deletion
from django.db import migrations, models

import speakers.models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_conference_coc_url_conference_donate_url_and_more"),
        ("speakers", "0009_pretix_reconcile_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakersettings",
            name="conference_timezone",
            field=models.CharField(
                default="UTC",
                help_text="The organizers' default display timezone; the conference itself has none.",
                max_length=64,
                validators=[speakers.models.validate_timezone],
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="organizers_email",
            field=models.EmailField(
                blank=True,
                help_text="Where unassigned organizer reminders go; blank sends them to every staff account.",
                max_length=254,
            ),
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("threshold_days", models.PositiveSmallIntegerField()),
                ("recipient", models.EmailField(max_length=254)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conference",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminder_logs",
                        to="portal.conference",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="speakers.checklistitem",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "threshold_days"), name="speakers_reminder_once"
                    )
                ],
            },
        ),
    ]
