# Generated by Django 5.2.13 on 2026-09-23 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_conference_coc_url_conference_donate_url_and_more"),
        ("speakers", "0009_general_checklist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitem",
            name="is_waiting",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="ready_gate_code",
            field=models.SlugField(
                blank=True, db_default="", default="", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="ready_override",
            field=models.CharField(
                blank=True,
                choices=[("OPEN", "Open it anyway"), ("HOLD", "Hold it shut")],
                db_default="",
                default="",
                help_text="An organizer's answer, which outranks every wait source.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="ready_rule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("session_scheduled", "The session has a slot"),
                    ("guide_published", "The guide it points at is published"),
                    ("registration_open", "Registration is set up on pretix"),
                ],
                db_default="",
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="template_waiting_note",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="waiting_reason",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="waits_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocks",
                to="speakers.checklistitem",
            ),
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="waits_for_line",
            field=models.ForeignKey(
                blank=True,
                help_text="The line whose item this one waits for; resolved to the item itself once that item exists.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocked_instances",
                to="speakers.checklisttemplateitem",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplateitem",
            name="ready_gate_code",
            field=models.SlugField(
                blank=True,
                db_default="",
                default="",
                help_text="Wait for a gate organizers flip, matched per edition by code so templates clone forward.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplateitem",
            name="ready_rule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("session_scheduled", "The session has a slot"),
                    ("guide_published", "The guide it points at is published"),
                    ("registration_open", "Registration is set up on pretix"),
                ],
                db_default="",
                default="",
                help_text="Wait for something the portal can check.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplateitem",
            name="waiting_note",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="What the speaker reads while it waits; blank uses the source's own wording.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplateitem",
            name="waits_for",
            field=models.ForeignKey(
                blank=True,
                help_text="Wait for the item made from another line, for the same presenter, to be done.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocks",
                to="speakers.checklisttemplateitem",
            ),
        ),
        migrations.CreateModel(
            name="ReadinessGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("code", models.SlugField(max_length=40)),
                (
                    "name",
                    models.CharField(
                        help_text="What organizers call it on the gates page.",
                        max_length=100,
                    ),
                ),
                (
                    "waiting_note",
                    models.CharField(
                        help_text='What a speaker reads while it is shut, e.g. "booking opens later".',
                        max_length=120,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_default="", default=""),
                ),
                ("is_open", models.BooleanField(db_default=False, default=False)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readiness_gates",
                        to="portal.conference",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="ready_gate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="speakers.readinessgate",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinessgate",
            constraint=models.UniqueConstraint(
                fields=("conference", "code"), name="speakers_gate_code_per_edition"
            ),
        ),
    ]
