# Generated by Django 5.2.13 on 2026-09-24 16:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_conference_coc_url_conference_donate_url_and_more"),
        ("speakers", "0010_readiness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="created_by_presenter",
            field=models.BooleanField(
                db_default=False,
                default=False,
                editable=False,
                help_text="A speaker added this session themselves, or proposed it; organizers did not type it in.",
            ),
        ),
        migrations.AddField(
            model_name="sessiontype",
            name="open_for_proposals",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Offered on the propose-a-session form, and to a speaker adding a session of their own. Off for the types nobody proposes, such as a break or the opening.",
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="proposals_intro_md",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text="Shown above the propose-a-session form: what you are looking for, and by when.",
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="proposals_open",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="While on, anyone with a portal account may propose a session, and speakers already on the program may add one.",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROPOSED", "Proposed"),
                    ("DRAFT", "Draft"),
                    ("INVITED", "Invited"),
                    ("CONFIRMED", "Confirmed"),
                    ("SCHEDULED", "Scheduled"),
                    ("PUBLISHED", "Published"),
                    ("CANCELLED", "Cancelled"),
                    ("REJECTED", "Not accepted"),
                ],
                default="DRAFT",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Not accepted"),
                        ],
                        db_default="PENDING",
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="portal.conference",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "presenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="speakers.presenter",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal",
                        to="speakers.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-id"],
            },
        ),
    ]
