# Generated by Django 5.2.13 on 2026-09-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0011_digest_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="handbook",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Where the guide lives, e.g. https://conference.pyladies.com/docs/",
            ),
        ),
        migrations.AlterField(
            model_name="handbook",
            name="body_md",
            field=models.TextField(
                blank=True, help_text="Optional note shown above the link. Markdown."
            ),
        ),
    ]
