# Generated by Django 5.2.13 on 2026-09-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0014_team_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="presenter",
            name="password_reminder_dismissed",
            field=models.BooleanField(
                default=False,
                help_text="The presenter chose to keep signing in with emailed codes.",
            ),
        ),
    ]
