# Generated by Django 5.2.13 on 2026-10-03 02:02

# A column saying when a file was shared, and a row per shared file each
# presenter has been told about (design §13.2). Both are seeded for what is
# already shared, so the first digest after the deploy announces only what
# is shared from now on, not months-old files as "new".

import django.db.models.deletion
from django.db import migrations, models


def start_quiet(apps, schema_editor):
    """Stamp every currently shared file with when it was last saved, and
    mark it told to every confirmed presenter on its session, whatever the
    session's state: a row only ever keeps a file out of a digest."""
    MediaAsset = apps.get_model("speakers", "MediaAsset")
    SessionPresenter = apps.get_model("speakers", "SessionPresenter")
    SharedFileNotice = apps.get_model("speakers", "SharedFileNotice")
    shared = MediaAsset.objects.filter(shared_with_speaker=True, status="READY")
    for asset in shared:
        MediaAsset.objects.filter(pk=asset.pk).update(shared_at=asset.modified_date)
    links = (
        SessionPresenter.objects.filter(
            confirmed_at__isnull=False, session__media_assets__in=shared
        )
        .select_related("presenter")
        .distinct()
    )
    notices = []
    by_session = {}
    for asset in shared:
        by_session.setdefault(asset.session_id, []).append(asset)
    for link in links:
        for asset in by_session.get(link.session_id, []):
            notices.append(
                SharedFileNotice(
                    conference_id=asset.conference_id,
                    presenter_id=link.presenter_id,
                    asset_id=asset.pk,
                    recipient=link.presenter.email,
                )
            )
    SharedFileNotice.objects.bulk_create(notices, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_conference_coc_url_conference_donate_url_and_more"),
        ("speakers", "0015_exports_thumbnails_transcription"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="shared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SharedFileNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="speakers.mediaasset",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shared_file_notices",
                        to="portal.conference",
                    ),
                ),
                (
                    "presenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_notices",
                        to="speakers.presenter",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("presenter", "asset"), name="speakers_file_notice_once"
                    )
                ],
            },
        ),
        # The table goes with the reverse of CreateModel above; nothing to undo.
        migrations.RunPython(start_quiet, migrations.RunPython.noop),
    ]
