# Generated by Django 5.2.13 on 2026-09-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0015_password_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitem",
            name="pending_notice",
            field=models.CharField(
                blank=True,
                choices=[("NEW", "New item"), ("CHANGED", "Changed item")],
                editable=False,
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="pending_since",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
