# Generated by Django 5.2.13 on 2026-10-08 02:01

import secrets

from django.db import migrations, models

import speakers.models


def settle_each_edition(apps, schema_editor):
    """Each edition gets its own preview key (AddField gave every row the
    same one), and the switch starts PUBLISHED where sessions were already
    public on the confirmed schedule, so nothing visible today disappears
    on deploy."""
    SpeakerSettings = apps.get_model("speakers", "SpeakerSettings")
    Session = apps.get_model("speakers", "Session")
    for row in SpeakerSettings.objects.all():
        row.preview_key = secrets.token_urlsafe(16)
        if (
            Session.objects.filter(
                conference_id=row.conference_id,
                is_public=True,
                published_slot__isnull=False,
            )
            .exclude(status="CANCELLED")
            .exists()
        ):
            row.program_visibility = "PUBLISHED"
        row.save(update_fields=["preview_key", "program_visibility"])


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0018_published_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakersettings",
            name="preview_key",
            field=models.CharField(
                blank=True,
                db_default="",
                default=speakers.models.new_preview_key,
                editable=False,
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="program_visibility",
            field=models.CharField(
                choices=[("INTERNAL", "Internal"), ("PUBLISHED", "Published")],
                db_default="INTERNAL",
                default="INTERNAL",
                help_text="The master switch (design §11.5): while internal, the public program is empty and the website shows it as coming soon.",
                max_length=16,
            ),
        ),
        migrations.RunPython(settle_each_edition, migrations.RunPython.noop),
    ]
