# Generated by Django 5.2.13 on 2026-10-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0018_published_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakersettings",
            name="preview_key",
            field=models.CharField(
                blank=True, db_default="", default="", editable=False, max_length=32
            ),
        ),
        migrations.AddField(
            model_name="speakersettings",
            name="program_visibility",
            field=models.CharField(
                choices=[("INTERNAL", "Internal"), ("PUBLISHED", "Published")],
                db_default="INTERNAL",
                default="INTERNAL",
                help_text="The master switch (design §11.5): while internal, the public program is empty and the website shows it as coming soon.",
                max_length=16,
            ),
        ),
    ]
