# Generated by Django 5.2.13 on 2026-10-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0019_program_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakersettings",
            name="api_allowed_origins",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text="Websites whose pages may read the public API from the browser, one origin per line, for example https://2026.conference.pyladies.com.",
            ),
        ),
    ]
