# Generated by Django 5.2.13 on 2026-10-08 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0019_program_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedOrigin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The site's address only, for example https://2026.conference.pyladies.com.",
                        verbose_name="website",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_origins",
                        to="speakers.speakersettings",
                    ),
                ),
            ],
            options={
                "ordering": ["url"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("settings", "url"), name="speakers_allowed_origin_once"
                    )
                ],
            },
        ),
    ]
