# Generated by Django 5.2.13 on 2026-10-08 17:28

from django.db import migrations, models

import portal.validators


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0020_allowed_origins"),
    ]

    operations = [
        migrations.AddField(
            model_name="presenter",
            name="discord_username",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="For the speaker role and channel on the conference Discord. Never shown on the public site.",
                max_length=32,
                validators=[portal.validators.validate_discord_username],
            ),
        ),
    ]
