# Generated by Django 5.1.7 on 2025-04-03 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation_date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='modified_date')),
            ],
        ),
    ]
