# Generated by Django 5.2.2 on 2025-06-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basemodel",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation_date"),
        ),
        migrations.AlterField(
            model_name="basemodel",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, verbose_name="modified_date"),
        ),
    ]
