# Generated by Django 5.1.7 on 2025-04-01 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemodel',
            options={},
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation_date'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='modified_date'),
        ),
    ]
