# Generated by Django 5.2.13 on 2026-06-11 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_basemodel_creation_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="portal.basemodel",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("pretix_event_slug", models.CharField(blank=True, max_length=100)),
                (
                    "sponsorship_goal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "donation_goal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("proposals_count", models.PositiveIntegerField(default=0)),
                ("volunteer_application_open", models.BooleanField(default=False)),
                ("sponsorship_open", models.BooleanField(default=False)),
                ("accepting_donations", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("banner_text", models.CharField(blank=True, max_length=255)),
                ("historical_snapshot", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-year"],
            },
            bases=("portal.basemodel",),
        ),
    ]
