# Generated by Django 5.1.13 on 2025-11-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_basemodel_creation_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundraisingGoal",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="portal.basemodel",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("donation", "Donation Goal"),
                            ("sponsorship", "Sponsorship Goal"),
                        ],
                        help_text="Type of fundraising goal",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target amount for this goal",
                        max_digits=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this goal is currently active"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description for this goal",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fundraising Goal",
                "verbose_name_plural": "Fundraising Goals",
                "ordering": ["goal_type"],
            },
            bases=("portal.basemodel",),
        ),
    ]
