# Generated by Django 5.2.13 on 2026-06-12 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_conference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="basemodel_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="+",
                serialize=False,
                to="portal.basemodel",
            ),
        ),
    ]
