# Generated by Django 5.1.13 on 2025-11-19 10:02

from decimal import Decimal

from django.db import migrations


def create_initial_fundraising_goals(apps, schema_editor):
    """Create initial fundraising goals with updated values."""
    FundraisingGoal = apps.get_model("portal", "FundraisingGoal")

    # Create donation goal - changed from 1000 to 2500 as per issue #275
    FundraisingGoal.objects.create(
        goal_type="donation",
        target_amount=Decimal("2500.00"),
        is_active=True,
        description="Individual donation goal for PyLadiesCon",
    )

    # Create sponsorship goal - keeping at 15000 as per current value
    FundraisingGoal.objects.create(
        goal_type="sponsorship",
        target_amount=Decimal("15000.00"),
        is_active=True,
        description="Sponsorship funding goal for PyLadiesCon",
    )


def reverse_initial_fundraising_goals(apps, schema_editor):
    """Remove initial fundraising goals."""
    FundraisingGoal = apps.get_model("portal", "FundraisingGoal")
    FundraisingGoal.objects.filter(goal_type__in=["donation", "sponsorship"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_fundraisinggoal"),
    ]

    operations = [
        migrations.RunPython(
            create_initial_fundraising_goals, reverse_initial_fundraising_goals
        ),
    ]
