# Generated by Django 5.2.13 on 2026-06-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_backfill_conferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="conference_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
