# Generated by Django 5.2.13 on 2026-06-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_conference_conference_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="coc_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conference",
            name="donate_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conference",
            name="schedule_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conference",
            name="sponsors_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
