[tool.djlint]
# https://www.djlint.com/docs/linter/
# H030 - Consider adding a meta description.
# H031 - Consider adding meta keywords.
ignore="H030,H031"
profile = "django"
custom_blocks="switch"
line_break_after_multiline_tag=true
use_gitignore = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "portal.settings"
testpaths = [ "tests" ]
pythonpath = [ "." ]

[tool.coverage.run]
omit = ["portal/settings.py"]
