# Generated by Django 5.2.8 on 2025-11-16 05:44

import django.db.models.deletion
from django.db import migrations, models

import attendee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portal", "0002_alter_basemodel_creation_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PretixOrder",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="portal.basemodel",
                    ),
                ),
                ("order_code", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                attendee.models.PretixOrderstatus["CANCELLED"],
                                "Cancelled",
                            ),
                            (attendee.models.PretixOrderstatus["PAID"], "Paid"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("cancellation_date", models.DateTimeField(blank=True, null=True)),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                ("last_modified", models.DateTimeField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "is_anonymous",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                ("event_slug", models.CharField(max_length=100, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
            ],
            bases=("portal.basemodel",),
        ),
    ]
