# Generated by Django 5.2.8 on 2025-11-20 06:06

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0001_initial"),
        ("portal", "0002_alter_basemodel_creation_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendeeProfile",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="portal.basemodel",
                    ),
                ),
                (
                    "job_role",
                    models.CharField(
                        blank=True,
                        help_text="Professional role/occupation",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country of residence",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Geographic region",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        help_text="Python/programming experience level",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        help_text="Spoken languages",
                        null=True,
                        size=None,
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "company_size",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "heard_about",
                    models.CharField(
                        blank=True,
                        help_text="How they heard about PyLadiesCon",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("raw_answers", models.JSONField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="attendee.pretixorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendee Profile",
                "verbose_name_plural": "Attendee Profiles",
            },
            bases=("portal.basemodel",),
        ),
    ]
