# Generated by Django 5.2.8 on 2025-11-29 21:07

import django.db.models.deletion
from django.db import migrations, models

import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0001_initial"),
        ("portal", "0002_alter_basemodel_creation_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendeeProfile",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="portal.basemodel",
                    ),
                ),
                (
                    "current_position",
                    portal.models.ChoiceArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("Engineer", "Engineer"),
                                ("Student/Intern", "Student/Intern"),
                                ("Other", "Other"),
                                ("Scientist", "Scientist"),
                                (
                                    "Engineering/Scientist Manager",
                                    "Engineering/Scientist Manager",
                                ),
                                ("Product Owner/Manager", "Product Owner/Manager"),
                                ("Hobbyist", "Hobbyist"),
                                ("I'm currently retired", "I'm currently retired"),
                                ("", ""),
                            ],
                            help_text="Current Position",
                            null=True,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Current Country",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="Current City", max_length=100, null=True
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        help_text="Python/programming experience level",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "may_share_email_with_sponsor",
                    models.BooleanField(
                        blank=True,
                        help_text="Permission to share email with sponsors",
                        null=True,
                    ),
                ),
                (
                    "expectation_from_event",
                    portal.models.ChoiceArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("Learn new things", "Learn new things"),
                                ("Networking", "Networking"),
                                (
                                    "Support community activities",
                                    "Support community activities",
                                ),
                                ("Share Knowledge", "Share Knowledge"),
                                ("Other", "Other"),
                            ],
                            help_text="Expectations from the event",
                            null=True,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "heard_about",
                    portal.models.ChoiceArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("Social Media", "Social Media"),
                                ("Other", "Other"),
                                ("Conferences", "Conferences"),
                                ("Local meetups", "Local meetups"),
                            ],
                            help_text="How did you hear about the event?",
                            max_length=255,
                            null=True,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "participated_in_previous_event",
                    portal.models.ChoiceArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("PyLadiesCon 2024", "PyLadiesCon 2024"),
                                ("PyLadiesCon 2023", "PyLadiesCon 2023"),
                                (
                                    "No, this is my first one",
                                    "No, this is my first one",
                                ),
                            ],
                            help_text="Have you participated in a previous event?",
                            null=True,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "pyladies_chapter",
                    models.CharField(
                        blank=True,
                        help_text="Your PyLadies chapter",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "age_range",
                    models.CharField(
                        blank=True, help_text="Age range", max_length=100, null=True
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        help_text="Organization you work for",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("raw_answers", models.JSONField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="attendee.pretixorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendee Profile",
                "verbose_name_plural": "Attendee Profiles",
            },
            bases=("portal.basemodel",),
        ),
    ]
