# Generated by Django 5.2.8 on 2025-12-05 00:11

from django.db import migrations, models

import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0002_attendeeprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendeeprofile",
            name="participated_in_previous_event",
            field=portal.models.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("PyLadiesCon 2024", "PyLadiesCon 2024"),
                        ("PyLadiesCon 2023", "PyLadiesCon 2023"),
                        ("No this is my first one", "No this is my first one"),
                    ],
                    help_text="Have you participated in a previous event?",
                    null=True,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
