# Generated by Django 5.2.13 on 2026-06-12 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0003_alter_attendeeprofile_participated_in_previous_event"),
        ("portal", "0004_alter_conference_basemodel_ptr"),
    ]

    operations = [
        migrations.AddField(
            model_name="pretixorder",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pretix_orders",
                to="portal.conference",
            ),
        ),
    ]
