# Generated by Django 5.2.13 on 2026-06-22 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0004_pretixorder_conference"),
        ("portal", "0005_backfill_conferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pretixorder",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pretix_orders",
                to="portal.conference",
            ),
        ),
    ]
