# Generated by Django 5.1.8 on 2025-05-29 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="portal.basemodel",
                    ),
                ),
                ("event_slug", models.CharField(blank=True)),
            ],
            bases=("portal.basemodel",),
        ),
    ]
