# Generated by Django 5.1.7 on 2025-06-16 23:06

import django.db.models.deletion
import volunteer.constants
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.basemodel')),
                ('short_name', models.CharField(max_length=40, verbose_name='name')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
            ],
            bases=('portal.basemodel',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.basemodel')),
                ('short_name', models.CharField(max_length=40, verbose_name='name')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
            ],
            bases=('portal.basemodel',),
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.basemodel')),
                ('application_status', models.CharField(choices=[(volunteer.constants.ApplicationStatus['PENDING'], volunteer.constants.ApplicationStatus['PENDING']), (volunteer.constants.ApplicationStatus['APPROVED'], volunteer.constants.ApplicationStatus['APPROVED']), (volunteer.constants.ApplicationStatus['REJECTED'], volunteer.constants.ApplicationStatus['REJECTED']), (volunteer.constants.ApplicationStatus['CANCELLED'], volunteer.constants.ApplicationStatus['CANCELLED'])], default=volunteer.constants.ApplicationStatus['PENDING'], max_length=50)),
                ('github_username', models.CharField(blank=True, max_length=50, null=True)),
                ('discord_username', models.CharField(default='', help_text='Required - Your Discord username for team communication', max_length=50, verbose_name='Discord username (required)')),
                ('instagram_username', models.CharField(blank=True, max_length=50, null=True)),
                ('bluesky_username', models.CharField(blank=True, max_length=100, null=True)),
                ('mastodon_url', models.CharField(blank=True, max_length=100, null=True)),
                ('x_username', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=100, null=True)),
                ('languages_spoken', models.CharField(blank=True, help_text='Comma-separated list of languages', max_length=255, null=True)),
                ('pyladies_chapter', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('availability_hours_per_week', models.PositiveIntegerField(default=1)),
                ('region', models.CharField(choices=[(volunteer.constants.Region['NO_REGION'], volunteer.constants.Region['NO_REGION']), (volunteer.constants.Region['NORTH_AMERICA'], volunteer.constants.Region['NORTH_AMERICA']), (volunteer.constants.Region['SOUTH_AMERICA'], volunteer.constants.Region['SOUTH_AMERICA']), (volunteer.constants.Region['EUROPE'], volunteer.constants.Region['EUROPE']), (volunteer.constants.Region['AFRICA'], volunteer.constants.Region['AFRICA']), (volunteer.constants.Region['ASIA'], volunteer.constants.Region['ASIA']), (volunteer.constants.Region['OCEANIA'], volunteer.constants.Region['OCEANIA'])], default=volunteer.constants.Region['NO_REGION'], max_length=50)),
                ('roles', models.ManyToManyField(blank=True, related_name='roles', to='volunteer.role', verbose_name='Roles')),
                ('teams', models.ManyToManyField(blank=True, related_name='members', to='volunteer.team', verbose_name='members')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('portal.basemodel',),
        ),
        migrations.AddField(
            model_name='team',
            name='team_leads',
            field=models.ManyToManyField(related_name='team_leads', to='volunteer.volunteerprofile', verbose_name='team leads'),
        ),
    ]
