# Generated by Django 5.1.8 on 2025-05-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0002_remove_volunteerprofile_coc_agreement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerprofile",
            name="discord_username",
            field=models.CharField(
                default="",
                help_text="Required - Your Discord username for team communication",
                max_length=50,
                verbose_name="Discord username (required)",
            ),
        ),
    ]
