# Generated by Django 5.1.8 on 2025-05-16 03:27

from django.db import migrations, models

import volunteer.constants


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0004_alter_volunteerprofile_languages_spoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteerprofile",
            name="timezone",
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="additional_comments",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="availability_hours_per_week",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="region",
            field=models.CharField(
                choices=[
                    (
                        volunteer.constants.Region["NO_REGION"],
                        volunteer.constants.Region["NO_REGION"],
                    ),
                    (
                        volunteer.constants.Region["NORTH_AMERICA"],
                        volunteer.constants.Region["NORTH_AMERICA"],
                    ),
                    (
                        volunteer.constants.Region["SOUTH_AMERICA"],
                        volunteer.constants.Region["SOUTH_AMERICA"],
                    ),
                    (
                        volunteer.constants.Region["EUROPE"],
                        volunteer.constants.Region["EUROPE"],
                    ),
                    (
                        volunteer.constants.Region["AFRICA"],
                        volunteer.constants.Region["AFRICA"],
                    ),
                    (
                        volunteer.constants.Region["ASIA"],
                        volunteer.constants.Region["ASIA"],
                    ),
                    (
                        volunteer.constants.Region["OCEANIA"],
                        volunteer.constants.Region["OCEANIA"],
                    ),
                ],
                default=volunteer.constants.Region["NO_REGION"],
                max_length=50,
            ),
        ),
    ]
