# Generated by Django 5.2.2 on 2025-06-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0005_remove_volunteerprofile_timezone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerprofile",
            name="teams",
            field=models.ManyToManyField(
                blank=True,
                related_name="members",
                to="volunteer.team",
                verbose_name="members",
            ),
        ),
    ]
