# Generated by Django 5.1.7 on 2025-07-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_alter_volunteerprofile_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='additional_comments',
        ),
    ]
