# Generated by Django 5.2.3 on 2025-10-03 03:57

from django.db import migrations, models

import volunteer.constants


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0006_alter_volunteerprofile_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="open_to_new_members",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="application_status",
            field=models.CharField(
                choices=[
                    (
                        volunteer.constants.ApplicationStatus["PENDING"],
                        volunteer.constants.ApplicationStatus["PENDING"],
                    ),
                    (
                        volunteer.constants.ApplicationStatus["APPROVED"],
                        volunteer.constants.ApplicationStatus["APPROVED"],
                    ),
                    (
                        volunteer.constants.ApplicationStatus["REJECTED"],
                        volunteer.constants.ApplicationStatus["REJECTED"],
                    ),
                    (
                        volunteer.constants.ApplicationStatus["CANCELLED"],
                        volunteer.constants.ApplicationStatus["CANCELLED"],
                    ),
                    (
                        volunteer.constants.ApplicationStatus["WAITLISTED"],
                        volunteer.constants.ApplicationStatus["WAITLISTED"],
                    ),
                ],
                default=volunteer.constants.ApplicationStatus["PENDING"],
                max_length=50,
            ),
        ),
    ]
