# Generated by Django 5.2.7 on 2025-10-28 03:18

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_basemodel_creation_date_and_more"),
        ("volunteer", "0007_team_open_to_new_members_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PyladiesChapter",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="portal.basemodel",
                    ),
                ),
                ("chapter_name", models.CharField(max_length=100)),
                ("chapter_description", models.CharField(max_length=100)),
                (
                    "chapter_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("chapter_website", models.URLField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("chapter_name"),
                        name="chapter_name",
                    )
                ],
            },
            bases=("portal.basemodel",),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chapter_member",
                to="volunteer.pyladieschapter",
            ),
        ),
    ]
