# Generated by Django 5.2.7 on 2025-10-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0008_pyladieschapter_volunteerprofile_chapter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteerprofile",
            name="pyladies_chapter",
        ),
    ]
