# Generated by Django 5.2.7 on 2025-11-04 02:58

from django.db import migrations

from volunteer.management.commands.migrate_volunteer_language import populate_language_choices

def populate_languages(apps, schema_editor):
    populate_language_choices()


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0010_language_alter_volunteerprofile_languages_spoken_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_languages, migrations.RunPython.noop)
    ]
