# Generated by Django 5.2.7 on 2025-11-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0011_populate_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="pyladieschapter",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="chapter_logos/"),
        ),
    ]
