# Generated by Django 5.2.13 on 2026-06-12 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_alter_conference_basemodel_ptr"),
        ("volunteer", "0012_pyladieschapter_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="portal.conference",
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="volunteer_profiles",
                to="portal.conference",
            ),
        ),
    ]
