# Generated by Django 5.2.13 on 2026-06-22 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_backfill_conferences"),
        ("volunteer", "0013_team_conference_volunteerprofile_conference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="portal.conference",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="volunteer_profiles",
                to="portal.conference",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="volunteerprofile",
            unique_together={("user", "conference")},
        ),
    ]
