# Generated by Django 5.2.13 on 2026-06-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0014_alter_team_conference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
    ]
