"""
This module contains a list of language choices based on the Wikipedia page
"List of language names" (https://en.wikipedia.org/wiki/List_of_language_names).

The list is used to replace Django's default LANGUAGES list for the languages_spoken field
in the VolunteerProfile model.

For languages that don't have standard ISO 639-1 two-letter codes, unique codes have been
invented following the pattern of existing codes.
"""

# List of language choices based on https://en.wikipedia.org/wiki/List_of_language_names
# Format: (language_code, language_name)
LANGUAGES = [
    ("aa", "Afar"),
    ("ab", "Abkhazian"),
    ("ae", "Avestan"),
    ("af", "Afrikaans"),
    ("ak", "Akan"),
    ("am", "Amharic"),
    ("an", "Aragonese"),
    ("ar", "Arabic"),
    ("as", "Assamese"),
    ("av", "Avaric"),
    ("ay", "Aymara"),
    ("az", "Azerbaijani"),
    ("ba", "Bashkir"),
    ("be", "Belarusian"),
    ("bg", "Bulgarian"),
    ("bh", "Bihari languages"),
    ("bi", "Bislama"),
    ("bm", "Bambara"),
    ("bn", "Bengali"),
    ("bo", "Tibetan"),
    ("br", "Breton"),
    ("bs", "Bosnian"),
    ("ca", "Catalan"),
    ("ce", "Chechen"),
    ("ch", "Chamorro"),
    ("co", "Corsican"),
    ("cr", "Cree"),
    ("cs", "Czech"),
    ("cu", "Church Slavic"),
    ("cv", "Chuvash"),
    ("cy", "Welsh"),
    ("da", "Danish"),
    ("de", "German"),
    ("dv", "Divehi"),
    ("dz", "Dzongkha"),
    ("ee", "Ewe"),
    ("el", "Greek"),
    ("en", "English"),
    ("eo", "Esperanto"),
    ("es", "Spanish"),
    ("et", "Estonian"),
    ("eu", "Basque"),
    ("fa", "Persian"),
    ("ff", "Fulah"),
    ("fi", "Finnish"),
    ("fj", "Fijian"),
    ("fo", "Faroese"),
    ("fr", "French"),
    ("fy", "Western Frisian"),
    ("ga", "Irish"),
    ("gd", "Gaelic"),
    ("gl", "Galician"),
    ("gn", "Guarani"),
    ("gu", "Gujarati"),
    ("gv", "Manx"),
    ("ha", "Hausa"),
    ("he", "Hebrew"),
    ("hi", "Hindi"),
    ("ho", "Hiri Motu"),
    ("hr", "Croatian"),
    ("ht", "Haitian"),
    ("hu", "Hungarian"),
    ("hy", "Armenian"),
    ("hz", "Herero"),
    ("ia", "Interlingua"),
    ("id", "Indonesian"),
    ("ie", "Interlingue"),
    ("ig", "Igbo"),
    ("ii", "Sichuan Yi"),
    ("ik", "Inupiaq"),
    ("io", "Ido"),
    ("is", "Icelandic"),
    ("it", "Italian"),
    ("iu", "Inuktitut"),
    ("ja", "Japanese"),
    ("jv", "Javanese"),
    ("ka", "Georgian"),
    ("kg", "Kongo"),
    ("ki", "Kikuyu"),
    ("kj", "Kuanyama"),
    ("kk", "Kazakh"),
    ("kl", "Kalaallisut"),
    ("km", "Khmer"),
    ("kn", "Kannada"),
    ("ko", "Korean"),
    ("kr", "Kanuri"),
    ("ks", "Kashmiri"),
    ("ku", "Kurdish"),
    ("kv", "Komi"),
    ("kw", "Cornish"),
    ("ky", "Kirghiz"),
    ("la", "Latin"),
    ("lb", "Luxembourgish"),
    ("lg", "Ganda"),
    ("li", "Limburgan"),
    ("ln", "Lingala"),
    ("lo", "Lao"),
    ("lt", "Lithuanian"),
    ("lu", "Luba-Katanga"),
    ("lv", "Latvian"),
    ("mg", "Malagasy"),
    ("mh", "Marshallese"),
    ("mi", "Maori"),
    ("mk", "Macedonian"),
    ("ml", "Malayalam"),
    ("mn", "Mongolian"),
    ("mr", "Marathi"),
    ("ms", "Malay"),
    ("mt", "Maltese"),
    ("my", "Burmese"),
    ("na", "Nauru"),
    ("nb", "Norwegian Bokmål"),
    ("nd", "North Ndebele"),
    ("ne", "Nepali"),
    ("ng", "Ndonga"),
    ("nl", "Dutch"),
    ("nn", "Norwegian Nynorsk"),
    ("no", "Norwegian"),
    ("nr", "South Ndebele"),
    ("nv", "Navajo"),
    ("ny", "Nyanja"),
    ("oc", "Occitan"),
    ("oj", "Ojibwa"),
    ("om", "Oromo"),
    ("or", "Oriya"),
    ("os", "Ossetian"),
    ("pa", "Punjabi"),
    ("pi", "Pali"),
    ("pl", "Polish"),
    ("ps", "Pushto"),
    ("pt", "Portuguese"),
    ("qu", "Quechua"),
    ("rm", "Romansh"),
    ("rn", "Rundi"),
    ("ro", "Romanian"),
    ("ru", "Russian"),
    ("rw", "Kinyarwanda"),
    ("sa", "Sanskrit"),
    ("sc", "Sardinian"),
    ("sd", "Sindhi"),
    ("se", "Northern Sami"),
    ("sg", "Sango"),
    ("si", "Sinhala"),
    ("sk", "Slovak"),
    ("sl", "Slovenian"),
    ("sm", "Samoan"),
    ("sn", "Shona"),
    ("so", "Somali"),
    ("sq", "Albanian"),
    ("sr", "Serbian"),
    ("ss", "Swati"),
    ("st", "Southern Sotho"),
    ("su", "Sundanese"),
    ("sv", "Swedish"),
    ("sw", "Swahili"),
    ("ta", "Tamil"),
    ("te", "Telugu"),
    ("tg", "Tajik"),
    ("th", "Thai"),
    ("ti", "Tigrinya"),
    ("tk", "Turkmen"),
    ("tl", "Tagalog"),
    ("tn", "Tswana"),
    ("to", "Tonga"),
    ("tr", "Turkish"),
    ("ts", "Tsonga"),
    ("tt", "Tatar"),
    ("tw", "Twi"),
    ("ty", "Tahitian"),
    ("ug", "Uighur"),
    ("uk", "Ukrainian"),
    ("ur", "Urdu"),
    ("uz", "Uzbek"),
    ("ve", "Venda"),
    ("vi", "Vietnamese"),
    ("vo", "Volapük"),
    ("wa", "Walloon"),
    ("wo", "Wolof"),
    ("xh", "Xhosa"),
    ("yi", "Yiddish"),
    ("yo", "Yoruba"),
    ("za", "Zhuang"),
    ("zh", "Chinese"),
    ("zu", "Zulu"),
    # Additional languages with invented codes
    ("ax", "Acehnese"),
    ("ad", "Adyghe"),
    ("ah", "Ahom"),
    ("aj", "Ainu"),
    ("al", "Akkadian"),
    ("ap", "Algonquian languages"),
    ("aq", "Ancient Egyptian"),
    ("ac", "Ancient Greek"),
    ("at", "Aramaic"),
    ("ao", "Asturian"),
    ("aw", "Awadhi"),
    ("bc", "Balochi"),
    ("bt", "Batak"),
    ("bj", "Beja"),
    ("bl", "Belarusian (Taraškievica)"),
    ("bp", "Bhojpuri"),
    ("by", "Buryat"),
    ("cp", "Cantonese"),
    ("ct", "Catalan (Valencian)"),
    ("cg", "Chichewa"),
    ("cl", "Classical Chinese"),
    ("cq", "Crimean Tatar"),
    ("dx", "Dalmatian"),
    ("dm", "Dhivehi"),
    ("dg", "Dogri"),
    ("dl", "Dungan"),
    ("em", "Egyptian Arabic"),
    ("ep", "Emilian-Romagnol"),
    ("ex", "Extremaduran"),
    ("fc", "Franco-Provençal"),
    ("fx", "Friulian"),
    ("gc", "Gan Chinese"),
    ("go", "Gothic"),
    ("gr", "Greenlandic"),
    ("hk", "Hakka Chinese"),
    ("hw", "Hawaiian"),
    ("hm", "Hmong"),
    ("hx", "Hokkien"),
    ("ix", "Ilokano"),
    ("iv", "Ingush"),
    ("jb", "Javanese (Basa Jawa)"),
    ("jp", "Judeo-Persian"),
    ("kc", "Kabardian"),
    ("kb", "Kabyle"),
    ("kp", "Kapampangan"),
    ("ku", "Kashubian"),
    ("kh", "Khasi"),
    ("kx", "Khoisan languages"),
    ("kd", "Komi-Permyak"),
    ("kz", "Konkani"),
    ("lc", "Ladino"),
    ("lt", "Latgalian"),
    ("lm", "Ligurian"),
    ("lp", "Limburgish"),
    ("lw", "Livonian"),
    ("lh", "Lojban"),
    ("lg", "Low German"),
    ("ls", "Lower Sorbian"),
    ("ma", "Maithili"),
    ("mc", "Manchu"),
    ("md", "Mandarin Chinese"),
    ("mp", "Mapudungun"),
    ("mw", "Marwari"),
    ("mx", "Min Nan"),
    ("mb", "Minangkabau"),
    ("mo", "Mohawk"),
    ("mu", "Moksha"),
    ("me", "Mon"),
    ("mv", "Montenegrin"),
    ("nc", "Nahuatl"),
    ("nm", "Nauruan"),
    ("nj", "Navajo"),
    ("nx", "Neapolitan"),
    ("np", "Nepal Bhasa"),
    ("nt", "Northern Sami"),
    ("ob", "Occitan (post 1500)"),
    ("od", "Odia"),
    ("ol", "Old Church Slavonic"),
    ("oe", "Old English"),
    ("of", "Old French"),
    ("oh", "Old High German"),
    ("on", "Old Norse"),
    ("op", "Old Persian"),
    ("ot", "Old Turkic"),
    ("ox", "Oromo"),
    ("ow", "Ossetian"),
    ("pc", "Pangasinan"),
    ("px", "Papiamento"),
    ("ph", "Pashto"),
    ("pd", "Pennsylvania German"),
    ("pm", "Piedmontese"),
    ("po", "Pontic Greek"),
    ("pr", "Proto-Indo-European"),
    ("pw", "Punjabi (Western)"),
    ("qc", "Quechua (additional dialects)"),
    ("rj", "Rajasthani"),
    ("rc", "Romani"),
    ("rx", "Rusyn"),
    ("sx", "Samogitian"),
    ("sp", "Santali"),
    ("sh", "Scots"),
    ("sg", "Scottish Gaelic (additional dialects)"),
    ("sb", "Serbo-Croatian"),
    ("sf", "Shanghainese"),
    ("sv", "Silesian"),
    ("sz", "Sicilian"),
    ("sy", "Syriac"),
    ("tx", "Tamasheq"),
    ("tm", "Tamashek"),
    ("tc", "Taos"),
    ("tb", "Tarifit"),
    ("tp", "Tok Pisin"),
    ("tu", "Tulu"),
    ("ud", "Udmurt"),
    ("us", "Upper Sorbian"),
    ("uy", "Uyghur (additional script)"),
    ("vx", "Venetian"),
    ("vp", "Veps"),
    ("wc", "Wu Chinese"),
    ("ya", "Yakut"),
    ("yu", "Yupik languages"),
]
