# Generated by Django 5.1.7 on 2025-04-03 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tier', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('contract_sent', models.BooleanField(default=False)),
                ('payment_received', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_file', models.FileField(upload_to='sponsorship_assets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sponsorship_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorship.sponsorshipapplication')),
            ],
        ),
    ]
