# Generated by Django 5.1.7 on 2025-07-10 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorshipProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                (
                    "sponsorship_type",
                    models.CharField(
                        choices=[
                            ("Champion", "Champion"),
                            ("Supporter", "Supporter"),
                            ("Connector", "Connector"),
                            ("Booster", "Booster"),
                            ("Partner", "Partner"),
                            ("Individual", "Individual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("logo", models.ImageField(upload_to="sponsor_logos/")),
                ("company_description", models.TextField()),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "additional_contacts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="additional_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "main_contact_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsorship_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
