# Generated by Django 5.1.7 on 2025-08-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshipprofile',
            name='amount_to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
