# Generated by Django 5.2.3 on 2025-07-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorshipprofile",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="sponsor_logos/"),
        ),
    ]
