# Generated by Django 5.1.7 on 2025-07-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sponsorship",
            "0002_rename_description_sponsorshipprofile_company_description_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="SponsorshipTier",
        ),
    ]
