# Generated by Django 5.2.3 on 2025-09-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0002_sponsorshiptier_and_more"),
        ("sponsorship", "0004_remove_sponsorshipprofile_sponsorship_type"),
    ]

    operations = []
