# Generated by Django 5.2.7 on 2025-10-26 02:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_basemodel_creation_date_and_more"),
        ("sponsorship", "0002_sponsorshiptier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsorshipprofile",
            name="application_status",
        ),
        migrations.RemoveField(
            model_name="sponsorshipprofile",
            name="id",
        ),
        migrations.RemoveField(
            model_name="sponsorshiptier",
            name="id",
        ),
        migrations.AddField(
            model_name="sponsorshipprofile",
            name="basemodel_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="portal.basemodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sponsorshipprofile",
            name="progress_status",
            field=models.IntegerField(
                choices=[
                    (1, "Not Contacted"),
                    (2, "Awaiting Response"),
                    (3, "Rejected"),
                    (4, "Accepted"),
                    (5, "Approved"),
                    (6, "Agreement Sent"),
                    (7, "Agreement Signed"),
                    (8, "Invoiced"),
                    (9, "Paid"),
                    (10, "Cancelled"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="sponsorshiptier",
            name="basemodel_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="portal.basemodel",
            ),
            preserve_default=False,
        ),
    ]
