# Generated by Django 5.1.7 on 2025-08-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0002_sponsorshipprofile_amount_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshipprofile',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('paid', 'Paid'), ('awaiting', 'Awaiting Payment')], default='not_paid', max_length=20),
        ),
    ]
