# Generated by Django 5.2.3 on 2025-09-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0002_sponsorshiptier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsorshipprofile",
            name="sponsorship_type",
        ),
    ]
