# Generated by Django 5.2.7 on 2025-10-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0003_remove_sponsorshipprofile_application_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorshipprofile",
            name="organization_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sponsorshipprofile",
            name="sponsor_contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sponsorshipprofile",
            name="sponsors_contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="sponsorshipprofile",
            name="sponsorship_override_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipprofile",
            name="company_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
