# Generated by Django 5.2.7 on 2025-11-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0004_sponsorshipprofile_organization_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorshipprofile",
            name="po_number",
            field=models.CharField(
                blank=True,
                help_text="Purchase Order number for the sponsorship contract and invoice",
                max_length=100,
                null=True,
            ),
        ),
    ]
