# Generated by Django 5.2.7 on 2025-11-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0004_sponsorshipprofile_organization_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorshipprofile",
            name="is_individual_donation",
            field=models.BooleanField(
                default=False,
                help_text="Check if this is an individual donation (not a corporate sponsorship)",
            ),
        ),
    ]
