# Generated by Django 5.2.7 on 2025-11-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0004_sponsorshipprofile_organization_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorshipprofile",
            name="progress_status",
            field=models.IntegerField(
                choices=[
                    (1, "Not Contacted"),
                    (2, "Awaiting Response"),
                    (3, "Rejected"),
                    (4, "Accepted"),
                    (5, "Approved"),
                    (6, "Agreement Sent"),
                    (7, "Agreement Signed"),
                    (8, "Invoiced"),
                    (9, "Paid"),
                    (10, "Cancelled"),
                ],
                default=1,
            ),
        ),
    ]
