# Generated by Django 5.2.7 on 2025-11-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0005_alter_sponsorshipprofile_progress_status"),
        ("sponsorship", "0005_sponsorshipprofile_po_number"),
    ]

    operations = []
