# Generated by Django 5.2.8 on 2025-11-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0005_alter_sponsorshipprofile_progress_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorshipprofile",
            name="po_number",
            field=models.CharField(
                blank=True,
                help_text="Purchase Order number for the sponsorship contract and invoice",
                max_length=100,
                null=True,
            ),
        ),
    ]
