# Generated by Django 5.2.8 on 2025-11-14 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_basemodel_creation_date_and_more"),
        ("sponsorship", "0006_sponsorshipprofile_po_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualDonation",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="portal.basemodel",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("donor_name", models.CharField(blank=True, max_length=255, null=True)),
                ("transaction_date", models.DateTimeField(blank=True, null=True)),
                (
                    "donation_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("donor_email", models.EmailField(max_length=254)),
                ("is_anonymous", models.BooleanField(default=False)),
            ],
            bases=("portal.basemodel",),
        ),
    ]
