# Generated by Django 5.2.8 on 2025-12-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0007_individualdonation"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorshipprofile",
            name="github_issue_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the GitHub issue tracking this sponsorship",
                null=True,
            ),
        ),
    ]
