# Generated by Django 5.2.13 on 2026-06-12 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_alter_conference_basemodel_ptr"),
        ("sponsorship", "0008_sponsorshipprofile_github_issue_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualdonation",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="individual_donations",
                to="portal.conference",
            ),
        ),
        migrations.AddField(
            model_name="sponsorshipprofile",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sponsorship_profiles",
                to="portal.conference",
            ),
        ),
        migrations.AddField(
            model_name="sponsorshiptier",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sponsorship_tiers",
                to="portal.conference",
            ),
        ),
    ]
