# Generated by Django 5.2.13 on 2026-06-22 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_backfill_conferences"),
        ("sponsorship", "0009_individualdonation_conference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualdonation",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="individual_donations",
                to="portal.conference",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipprofile",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sponsorship_profiles",
                to="portal.conference",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshiptier",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sponsorship_tiers",
                to="portal.conference",
            ),
        ),
    ]
