# Generated by Django 5.2.13 on 2026-06-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0010_alter_individualdonation_conference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorshiptier",
            name="sponsor_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional maximum number of sponsors accepted for this tier.",
                null=True,
            ),
        ),
    ]
