# Generated by Django 5.1.7 on 2025-04-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalprofile',
            name='tos_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
