# Generated by Django 5.1.8 on 2025-05-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal_account", "0002_portalprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalprofile",
            name="tos_agreement",
            field=models.BooleanField(default=False),
        ),
    ]
